export const SHOPPING_LIST = [
  {
    id: 1,
    name: "사과",
    image: "../../assets/apple.jpeg",
    category: "과일",
    price: 1000,
  },
  {
    id: 2,
    name: "레몬",
    image: "../../assets/lemon.jpeg",
    category: "과일",
    price: 3000,
  },
  {
    id: 3,
    name: "오렌지",
    image: "../../assets/orange.jpeg",
    category: "과일",
    price: 5000,
  },
  {
    id: 4,
    name: "파인애플",
    image: "../../assets/pineapple.jpeg",
    category: "과일",
    price: 7000,
  },
  {
    id: 5,
    name: "망고",
    image: "../../assets/mango.jpeg",
    category: "과일",
    price: 10000,
  },
  {
    id: 6,
    name: "카이센동",
    image: "../../assets/kaisendon.jpeg",
    category: "일식",
    price: 15000,
  },
  {
    id: 7,
    name: "돈까스",
    image: "../../assets/porkcutlet.jpeg",
    category: "일식",
    price: 12000,
  },
  {
    id: 8,
    name: "스시",
    image: "../../assets/sushi.jpeg",
    category: "일식",
    price: 50000,
  },
  {
    id: 9,
    name: "돈까스 책",
    image: "../../assets/porkcutlet_book.jpeg",
    category: "서적",
    price: 13000,
  },
  {
    id: 10,
    name: "스시 책",
    image: "../../assets/sushi_book.jpeg",
    category: "서적",
    price: 14000,
  },
];
