export const selectors = {
  mainIcon: document.querySelector("#main-logo"),
  hamburgerIcon: document.querySelector("#hamburger-logo"),
  aside: document.querySelector("aside"),
  cartLink: document.querySelector("#cart-link"),
  arrowIcon: document.querySelector("#arrow-icon"),
  tableBody: document.querySelector(".cart-table-container table tbody"),
  selectAllCheckbox: document.querySelector('thead input[type="checkbox"]'),
  purchaseBtn: document.querySelector("#purchase-button"),
  purchaseModal: document.querySelector("#purchase-modal"),
  modalContainer: document.querySelector(".modal-content-container"),
  modalPriceContainer: document.querySelector(".modal-price-container"),
  modalPurchaseBtn: document.querySelector("#modal-purchase-button"),
  modalCloseBtn: document.querySelector("#modal-close-button"),
  homeBtn: document.querySelector("#home-button"),
};
